name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      # If your repo is published at https://<user>.github.io/<repo>, set PUBLIC_BASE_PATH to '/<repo>'
      PUBLIC_BASE_PATH: '/expense-split-pwa'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          # Use Node 20.x to match project plugin engine requirements
          node-version: '20.19.0'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NODE_ENV: ${{ env.NODE_ENV }}
          PUBLIC_BASE_PATH: ${{ env.PUBLIC_BASE_PATH }}
        
          PUBLIC_ODOO_URL: ${{ secrets.PUBLIC_ODOO_URL }}
          PUBLIC_ODOO_DB: ${{ secrets.PUBLIC_ODOO_DB }}
          PUBLIC_ODOO_USERNAME: ${{ secrets.PUBLIC_ODOO_USERNAME }}
          PUBLIC_ODOO_PASSWORD: ${{ secrets.PUBLIC_ODOO_PASSWORD }}
          PUBLIC_ODOO_API_KEY: ${{ secrets.PUBLIC_ODOO_API_KEY }}
          PUBLIC_ODOO_EXPENSE_MODEL: ${{ secrets.PUBLIC_ODOO_EXPENSE_MODEL }}

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          keep_files: false
